apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-task-manager
  labels:
    app: frontend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always

      containers:
        - name: frontend
          image: omarmarrakchi/task-manager-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          # Liveness Probe : verifier que Nginx repond
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness Probe : verifier que le frontend est pret
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
