apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: devops-task-manager
  labels:
    app: postgres
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce           # un seul noeud peut ecrire a la fois
  persistentVolumeReclaimPolicy: Retain   # garder les donnees apres suppression du PVC
  storageClassName: manual
  hostPath:
    path: /data/postgres      # chemin sur le noeud K8s
