[master]
k8s-master ansible_host=192.168.198.134

[workers]
k8s-worker-1 ansible_host=192.168.198.136
k8s-worker-2 ansible_host=192.168.198.137

[k8s:children]
master
workers

[all:vars]
ansible_user=omar
ansible_password=omar
ansible_become=true
ansible_become_method=sudo
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
